### ISSUE TITLE
prevent template nesting

### ISSUE THREAD

**Issue by fervanrijswijk** [mdvanes/grunt-kot2html#1]
When having a template which already has a small part of js-templating inside the file, script-tags will get nested. To prevent this, you should check the content of the html file for existing <script> tags and write that part directly into the output file.

**Comment by mdvanes** [comment]
This issue is about source template files that themselves contain inline template files. The plugin succesfully converts this to a template inside of a template, but the problem was that the editor does not accept this, although it works in practice.

E.g. a template file "page.html":

``` html
<script type="text/html" id="foo">
<h1>my header</h1>
</script>
<div data-bind="template: {name: 'foo'}">
</div>
```

is converted to 

``` html
<script type="text/html" id="page">
<script type="text/html" id="foo">
<h1>my header</h1>
</script>
<div data-bind="template: {name: 'foo'}">
</div>
</script>
```

This won't be fixed, because it is recommended not to use inline templates in template files. It would be sufficient to convert to inline template to a separate template file.
